import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it } from 'vitest';
import ProblemTreatmentGuide from './ProblemTreatmentGuide';
import { getProblemBySlug } from '../data/problemSeoData';
import { getProblemTreatmentGuide } from '../data/problemTreatmentGuides';
afterEach(cleanup);
it('navigates treatments with the shared material tabs and preserves local downloads', () => {
  const guide = getProblemTreatmentGuide(getProblemBySlug('manchas-cafe-sofa')!);
  const {container} = render(<ProblemTreatmentGuide guide={guide} slug="manchas-cafe-sofa" />);
  expect(screen.getAllByRole('tabpanel')).toHaveLength(1);
  expect(screen.getByRole('tabpanel').textContent).toContain('leite ou açúcar');
  fireEvent.click(screen.getByRole('tab', {name:/Tratar/}));
  expect(screen.getAllByRole('tabpanel')).toHaveLength(1);
  expect(screen.getByRole('tabpanel').textContent).toContain('resíduos da bebida');
  fireEvent.click(screen.getByRole('button', {name:'Etapa anterior'}));
  expect(screen.getByRole('tabpanel').textContent).toContain('leite ou açúcar');
  fireEvent.click(screen.getByRole('button', {name:'Próxima etapa'}));
  expect(screen.getByRole('tabpanel').textContent).toContain('resíduos da bebida');
  fireEvent.keyDown(screen.getByRole('tab', {name:/Tratar/}), {key:'ArrowRight'});
  expect(screen.getByRole('tab', {name:/Finalizar/}).getAttribute('aria-selected')).toBe('true');
  expect([...container.querySelectorAll('a[download]')].map(a => a.getAttribute('href'))).toEqual([...new Set(guide.steps.map(s => s.image))]);
});
