// Gerado a partir de src/lib/calendarServices.ts (placeIndex): os concelhos e
// freguesias que o CRM usa para saber a região de um serviço. Não se edita à
// mão. Quando o teste src/lib/teamCalendarScript.test.ts falhar por causa
// deste ficheiro, corre `npx vitest run src/lib/teamCalendarScript.test.ts -u`
// e cola o resultado no ficheiro Lugares do projeto no Apps Script.
var LUGARES = {
  concelhos: [
    ["porto","Porto"],
    ["matosinhos","Porto"],
    ["maia","Porto"],
    ["vila nova de gaia","Porto"],
    ["gondomar","Porto"],
    ["valongo","Porto"],
    ["povoa de varzim","Porto"],
    ["vila do conde","Porto"],
    ["paredes","Porto"],
    ["penafiel","Porto"],
    ["lousada","Porto"],
    ["pacos de ferreira","Porto"],
    ["felgueiras","Porto"],
    ["santo tirso","Porto"],
    ["trofa","Porto"],
    ["espinho","Porto"],
    ["arouca","Porto"],
    ["santa maria da feira","Porto"],
    ["sao joao da madeira","Porto"],
    ["oliveira de azemeis","Porto"],
    ["ovar","Porto"],
    ["aveiro","Porto"],
    ["coimbra","Porto"],
    ["braga","Braga"],
    ["guimaraes","Braga"],
    ["vila nova de famalicao","Braga"],
    ["barcelos","Braga"],
    ["viana do castelo","Braga"],
    ["povoa de lanhoso","Braga"],
    ["fafe","Braga"],
    ["esposende","Braga"],
    ["lisboa","Lisboa"],
    ["amadora","Lisboa"],
    ["odivelas","Lisboa"],
    ["oeiras","Lisboa"],
    ["cascais","Lisboa"],
    ["sintra","Lisboa"],
    ["loures","Lisboa"],
    ["almada","Lisboa"],
    ["seixal","Lisboa"],
    ["vila franca de xira","Lisboa"],
    ["barreiro","Lisboa"],
    ["moita","Lisboa"],
    ["mafra","Lisboa"],
    ["setubal","Lisboa"],
    ["montijo","Lisboa"],
    ["alcochete","Lisboa"],
    ["palmela","Lisboa"],
    ["sesimbra","Lisboa"],
    ["alcacer do sal","Lisboa"],
    ["grandola","Lisboa"],
    ["santiago do cacem","Lisboa"],
    ["sines","Lisboa"],
    ["faro","Algarve"],
    ["loule","Algarve"],
    ["albufeira","Algarve"],
    ["olhao","Algarve"],
    ["sao bras de alportel","Algarve"],
    ["silves","Algarve"],
    ["lagoa","Algarve"],
    ["tavira","Algarve"],
    ["portimao","Algarve"],
    ["lagos","Algarve"],
    ["vila real de santo antonio","Algarve"],
    ["castro marim","Algarve"],
    ["monchique","Algarve"],
    ["aljezur","Algarve"],
    ["vila do bispo","Algarve"],
    ["alcoutim","Algarve"],
    ["gaia","Porto"],
    ["viana","Braga"],
    ["povoa","Porto"],
    ["aguas santas","Porto"],
    ["boavista","Porto"],
    ["campo alegre","Porto"],
    ["foz do douro","Porto"],
    ["antas","Porto"],
    ["charneca da caparica","Lisboa"],
    ["miratejo","Lisboa"],
    ["azambuja","Lisboa"],
    ["pucarica","Lisboa"],
    ["carvoeiro","Algarve"],
    ["montegordo","Algarve"],
    ["pedras del rei","Algarve"],
    ["pedras del rey","Algarve"],
    ["algarve","Algarve"],
  ],
  freguesias: [
    ["paranhos","Porto"],
    ["ramalde","Porto"],
    ["bonfim","Porto"],
    ["campanha","Porto"],
    ["cedofeita","Porto"],
    ["lordelo do ouro","Porto"],
    ["aldoar","Porto"],
    ["nevogilde","Porto"],
    ["massarelos","Porto"],
    ["miragaia","Porto"],
    ["santo ildefonso","Porto"],
    ["sao nicolau","Porto"],
    ["vitoria","Porto"],
    ["leca da palmeira","Porto"],
    ["sao mamede de infesta","Porto"],
    ["senhora da hora","Porto"],
    ["custoias","Porto"],
    ["leca do balio","Porto"],
    ["guifoes","Porto"],
    ["perafita","Porto"],
    ["lavra","Porto"],
    ["santa cruz do bispo","Porto"],
    ["cidade da maia","Porto"],
    ["castelo da maia","Porto"],
    ["moreira","Porto"],
    ["silva escura","Porto"],
    ["folgosa","Porto"],
    ["vila nova da telha","Porto"],
    ["milheiros","Porto"],
    ["mafamude","Porto"],
    ["santa marinha","Porto"],
    ["afurada","Porto"],
    ["canidelo","Porto"],
    ["madalena","Porto"],
    ["valadares","Porto"],
    ["gulpilhares","Porto"],
    ["sao felix da marinha","Porto"],
    ["oliveira do douro","Porto"],
    ["vilar do paraiso","Porto"],
    ["vilar de andorinho","Porto"],
    ["avintes","Porto"],
    ["canelas","Porto"],
    ["pedroso","Porto"],
    ["perosinho","Porto"],
    ["grijo","Porto"],
    ["sermonde","Porto"],
    ["baguim do monte","Porto"],
    ["fanzeres","Porto"],
    ["sao pedro da cova","Porto"],
    ["valbom","Porto"],
    ["gondomar centro","Porto"],
    ["jovim","Porto"],
    ["foz do sousa","Porto"],
    ["lomba","Porto"],
    ["covelo","Porto"],
    ["melres","Porto"],
    ["medas","Porto"],
    ["valongo centro","Porto"],
    ["ermesinde","Porto"],
    ["alfena","Porto"],
    ["sobrado","Porto"],
    ["paredes centro","Porto"],
    ["rebordosa","Porto"],
    ["baltar","Porto"],
    ["aguiar de sousa","Porto"],
    ["cete","Porto"],
    ["paco de sousa","Porto"],
    ["penafiel centro","Porto"],
    ["bustelo","Porto"],
    ["guilhufe","Porto"],
    ["marecos","Porto"],
    ["rio de moinhos","Porto"],
    ["lousada centro","Porto"],
    ["lustosa","Porto"],
    ["caide de rei","Porto"],
    ["pacos de ferreira centro","Porto"],
    ["freamunde","Porto"],
    ["frazao","Porto"],
    ["carvalhosa","Porto"],
    ["seroa","Porto"],
    ["felgueiras centro","Porto"],
    ["margaride","Porto"],
    ["lixa","Porto"],
    ["barrosas","Porto"],
    ["idaes","Porto"],
    ["santo tirso centro","Porto"],
    ["sao tome de negrelos","Porto"],
    ["vilarinho","Porto"],
    ["negrelos","Porto"],
    ["trofa centro","Porto"],
    ["sao romao do coronado","Porto"],
    ["sao martinho de bougado","Porto"],
    ["guidoes","Porto"],
    ["alvarelhos","Porto"],
    ["povoa de varzim centro","Porto"],
    ["aver-o-mar","Porto"],
    ["agucadoura","Porto"],
    ["navais","Porto"],
    ["beiriz","Porto"],
    ["argivai","Porto"],
    ["vila do conde centro","Porto"],
    ["azurara","Porto"],
    ["mindelo","Porto"],
    ["labruge","Porto"],
    ["modivas","Porto"],
    ["espinho centro","Porto"],
    ["silvalde","Porto"],
    ["anta","Porto"],
    ["paramos","Porto"],
    ["guetim","Porto"],
    ["arouca centro","Porto"],
    ["escariz","Porto"],
    ["urro","Porto"],
    ["alvarenga","Porto"],
    ["moldes","Porto"],
    ["lourosa","Porto"],
    ["fiaes","Porto"],
    ["argoncilhe","Porto"],
    ["mozelos","Porto"],
    ["santa maria de lamas","Porto"],
    ["nogueira da regedoura","Porto"],
    ["sao paio de oleiros","Porto"],
    ["pacos de brandao","Porto"],
    ["rio meao","Porto"],
    ["sao joao de ver","Porto"],
    ["arrifana","Porto"],
    ["milheiros de poiares","Porto"],
    ["cucujaes","Porto"],
    ["sao roque","Porto"],
    ["nogueira do cravo","Porto"],
    ["macieira de sarnes","Porto"],
    ["cesar","Porto"],
    ["fajoes","Porto"],
    ["carregosa","Porto"],
    ["loureiro","Porto"],
    ["pinheiro da bemposta","Porto"],
    ["esmoriz","Porto"],
    ["cortegaca","Porto"],
    ["maceda","Porto"],
    ["arada","Porto"],
    ["furadouro","Porto"],
    ["valega","Porto"],
    ["gloria","Porto"],
    ["vera cruz","Porto"],
    ["esgueira","Porto"],
    ["sao bernardo","Porto"],
    ["aradas","Porto"],
    ["santa joana","Porto"],
    ["oliveirinha","Porto"],
    ["cacia","Porto"],
    ["eixo","Porto"],
    ["eirol","Porto"],
    ["requeixo","Porto"],
    ["nossa senhora de fatima","Porto"],
    ["nariz","Porto"],
    ["sao jacinto","Porto"],
    ["se nova","Porto"],
    ["santa cruz","Porto"],
    ["almedina","Porto"],
    ["sao bartolomeu","Porto"],
    ["santo antonio dos olivais","Porto"],
    ["sao silvestre","Porto"],
    ["trouxemil","Porto"],
    ["torre de vilela","Porto"],
    ["souselas","Porto"],
    ["cernache","Porto"],
    ["botao","Porto"],
    ["castelo viegas","Porto"],
    ["torres do mondego","Porto"],
    ["antuzede","Porto"],
    ["vil de matos","Porto"],
    ["assafarge","Porto"],
    ["antanhol","Porto"],
    ["sao martinho do bispo","Porto"],
    ["ribeira de frades","Porto"],
    ["eiras","Porto"],
    ["sao paulo de frades","Porto"],
    ["sao martinho de arvore","Porto"],
    ["lamarosa","Porto"],
    ["brasfemes","Porto"],
    ["ceira","Porto"],
    ["sao joao do campo","Porto"],
    ["almalagues","Porto"],
    ["taveiro","Porto"],
    ["ameal","Porto"],
    ["arzila","Porto"],
    ["santa maria maior","Lisboa"],
    ["misericordia","Lisboa"],
    ["santo antonio","Lisboa"],
    ["sao vicente","Lisboa"],
    ["arroios","Lisboa"],
    ["penha de franca","Lisboa"],
    ["beato","Lisboa"],
    ["marvila","Lisboa"],
    ["parque das nacoes","Lisboa"],
    ["areeiro","Lisboa"],
    ["alvalade","Lisboa"],
    ["avenidas novas","Lisboa"],
    ["campo de ourique","Lisboa"],
    ["estrela","Lisboa"],
    ["campolide","Lisboa"],
    ["alcantara","Lisboa"],
    ["belem","Lisboa"],
    ["ajuda","Lisboa"],
    ["benfica","Lisboa"],
    ["sao domingos de benfica","Lisboa"],
    ["carnide","Lisboa"],
    ["lumiar","Lisboa"],
    ["olivais","Lisboa"],
    ["cascais e estoril","Lisboa"],
    ["estoril","Lisboa"],
    ["alcabideche","Lisboa"],
    ["carcavelos e parede","Lisboa"],
    ["carcavelos","Lisboa"],
    ["parede","Lisboa"],
    ["sao domingos de rana","Lisboa"],
    ["oeiras e sao juliao da barra","Lisboa"],
    ["sao juliao da barra","Lisboa"],
    ["alges, linda-a-velha e cruz quebrada","Lisboa"],
    ["alges","Lisboa"],
    ["linda-a-velha","Lisboa"],
    ["linda","Lisboa"],
    ["velha","Lisboa"],
    ["cruz quebrada","Lisboa"],
    ["carnaxide e queijas","Lisboa"],
    ["carnaxide","Lisboa"],
    ["queijas","Lisboa"],
    ["barcarena","Lisboa"],
    ["porto salvo","Lisboa"],
    ["sintra (vila)","Lisboa"],
    ["agualva e mira-sintra","Lisboa"],
    ["agualva","Lisboa"],
    ["mira-sintra","Lisboa"],
    ["algueirao-mem martins","Lisboa"],
    ["algueirao","Lisboa"],
    ["mem martins","Lisboa"],
    ["casal de cambra","Lisboa"],
    ["cacem e sao marcos","Lisboa"],
    ["cacem","Lisboa"],
    ["sao marcos","Lisboa"],
    ["massama e monte abraao","Lisboa"],
    ["massama","Lisboa"],
    ["monte abraao","Lisboa"],
    ["queluz e belas","Lisboa"],
    ["queluz","Lisboa"],
    ["belas","Lisboa"],
    ["rio de mouro","Lisboa"],
    ["sao joao das lampas e terrugem","Lisboa"],
    ["sao joao das lampas","Lisboa"],
    ["terrugem","Lisboa"],
    ["colares","Lisboa"],
    ["almargem do bispo, pero pinheiro e montelavar","Lisboa"],
    ["almargem do bispo","Lisboa"],
    ["pero pinheiro","Lisboa"],
    ["montelavar","Lisboa"],
    ["almada, cova da piedade, pragal e cacilhas","Lisboa"],
    ["cova da piedade","Lisboa"],
    ["pragal","Lisboa"],
    ["cacilhas","Lisboa"],
    ["caparica e trafaria","Lisboa"],
    ["caparica","Lisboa"],
    ["trafaria","Lisboa"],
    ["costa da caparica","Lisboa"],
    ["charneca de caparica e sobreda","Lisboa"],
    ["charneca de caparica","Lisboa"],
    ["sobreda","Lisboa"],
    ["laranjeiro e feijo","Lisboa"],
    ["laranjeiro","Lisboa"],
    ["feijo","Lisboa"],
    ["setubal (centro historico)","Lisboa"],
    ["sado","Lisboa"],
    ["gambia-pontes-alto da guerra","Lisboa"],
    ["gambia","Lisboa"],
    ["pontes","Lisboa"],
    ["alto da guerra","Lisboa"],
    ["azeitao","Lisboa"],
    ["aguas livres","Lisboa"],
    ["alfragide","Lisboa"],
    ["encosta do sol","Lisboa"],
    ["falagueira-venda nova","Lisboa"],
    ["falagueira","Lisboa"],
    ["venda nova","Lisboa"],
    ["mina de agua","Lisboa"],
    ["venteira","Lisboa"],
    ["povoa de santo adriao e olival basto","Lisboa"],
    ["povoa de santo adriao","Lisboa"],
    ["olival basto","Lisboa"],
    ["ramada e canecas","Lisboa"],
    ["ramada","Lisboa"],
    ["canecas","Lisboa"],
    ["pontinha e famoes","Lisboa"],
    ["pontinha","Lisboa"],
    ["famoes","Lisboa"],
    ["sacavem e prior velho","Lisboa"],
    ["sacavem","Lisboa"],
    ["prior velho","Lisboa"],
    ["santa iria de azoia, sao joao da talha e bobadela","Lisboa"],
    ["santa iria de azoia","Lisboa"],
    ["sao joao da talha","Lisboa"],
    ["bobadela","Lisboa"],
    ["camarate, unhos e apelacao","Lisboa"],
    ["camarate","Lisboa"],
    ["unhos","Lisboa"],
    ["apelacao","Lisboa"],
    ["santo antonio dos cavaleiros e frielas","Lisboa"],
    ["santo antonio dos cavaleiros","Lisboa"],
    ["frielas","Lisboa"],
    ["bucelas","Lisboa"],
    ["fanhoes","Lisboa"],
    ["lousa","Lisboa"],
    ["moscavide e portela","Lisboa"],
    ["moscavide","Lisboa"],
    ["alverca do ribatejo","Lisboa"],
    ["povoa de santa iria e forte da casa","Lisboa"],
    ["povoa de santa iria","Lisboa"],
    ["forte da casa","Lisboa"],
    ["alhandra, sao joao dos montes e calhandriz","Lisboa"],
    ["alhandra","Lisboa"],
    ["sao joao dos montes","Lisboa"],
    ["calhandriz","Lisboa"],
    ["vialonga","Lisboa"],
    ["castanheira do ribatejo e cachoeiras","Lisboa"],
    ["castanheira do ribatejo","Lisboa"],
    ["cachoeiras","Lisboa"],
    ["barreiro e lavradio","Lisboa"],
    ["lavradio","Lisboa"],
    ["alto do seixalinho, santo andre e verderena","Lisboa"],
    ["alto do seixalinho","Lisboa"],
    ["santo andre","Lisboa"],
    ["verderena","Lisboa"],
    ["palhais e coina","Lisboa"],
    ["palhais","Lisboa"],
    ["coina","Lisboa"],
    ["baixa da banheira e vale da amoreira","Lisboa"],
    ["baixa da banheira","Lisboa"],
    ["vale da amoreira","Lisboa"],
    ["alhos vedros","Lisboa"],
    ["gaio-rosario e sarilhos pequenos","Lisboa"],
    ["gaio-rosario","Lisboa"],
    ["rosario","Lisboa"],
    ["sarilhos pequenos","Lisboa"],
    ["ericeira","Lisboa"],
    ["malveira e sao miguel de alcainca","Lisboa"],
    ["malveira","Lisboa"],
    ["sao miguel de alcainca","Lisboa"],
    ["venda do pinheiro e santo estevao das gales","Lisboa"],
    ["venda do pinheiro","Lisboa"],
    ["santo estevao das gales","Lisboa"],
    ["seixal, arrentela e aldeia de paio pires","Lisboa"],
    ["arrentela","Lisboa"],
    ["aldeia de paio pires","Lisboa"],
    ["amora","Lisboa"],
    ["corroios","Lisboa"],
    ["fernao ferro","Lisboa"],
    ["montijo e afonsoeiro","Lisboa"],
    ["afonsoeiro","Lisboa"],
    ["alto estanqueiro-jardia","Lisboa"],
    ["alto estanqueiro","Lisboa"],
    ["jardia","Lisboa"],
    ["canha","Lisboa"],
    ["pegoes","Lisboa"],
    ["sarilhos grandes","Lisboa"],
    ["samouco","Lisboa"],
    ["sao francisco","Lisboa"],
    ["pinhal novo","Lisboa"],
    ["poceirao e marateca","Lisboa"],
    ["poceirao","Lisboa"],
    ["marateca","Lisboa"],
    ["quinta do anjo","Lisboa"],
    ["sesimbra (castelo) e quinta do conde","Lisboa"],
    ["sesimbra (castelo)","Lisboa"],
    ["quinta do conde","Lisboa"],
    ["santiago","Lisboa"],
    ["comporta","Lisboa"],
    ["torrao","Lisboa"],
    ["troia","Lisboa"],
    ["melides","Lisboa"],
    ["vila nova de santo andre","Lisboa"],
    ["cercal do alentejo","Lisboa"],
    ["ermidas-sado","Lisboa"],
    ["ermidas","Lisboa"],
    ["porto covo","Lisboa"],
    ["faro (se e sao pedro)","Algarve"],
    ["faro (se","Algarve"],
    ["sao pedro)","Algarve"],
    ["conceicao de faro","Algarve"],
    ["estoi","Algarve"],
    ["montenegro","Algarve"],
    ["santa barbara de nexe","Algarve"],
    ["loule (centro)","Algarve"],
    ["quarteira","Algarve"],
    ["vilamoura","Algarve"],
    ["almancil","Algarve"],
    ["quinta do lago","Algarve"],
    ["vale do lobo","Algarve"],
    ["boliqueime","Algarve"],
    ["alte, ameixial e salir","Algarve"],
    ["alte","Algarve"],
    ["ameixial","Algarve"],
    ["salir","Algarve"],
    ["albufeira e olhos de agua","Algarve"],
    ["olhos de agua","Algarve"],
    ["ferreiras","Algarve"],
    ["guia","Algarve"],
    ["paderne","Algarve"],
    ["quelfes","Algarve"],
    ["moncarapacho e fuseta","Algarve"],
    ["moncarapacho","Algarve"],
    ["fuseta","Algarve"],
    ["pechao","Algarve"],
    ["algoz e tunes","Algarve"],
    ["algoz","Algarve"],
    ["tunes","Algarve"],
    ["armacao de pera","Algarve"],
    ["pera","Algarve"],
    ["sao bartolomeu de messines","Algarve"],
    ["sao marcos da serra","Algarve"],
    ["lagoa e carvoeiro","Algarve"],
    ["estombar e parchal","Algarve"],
    ["estombar","Algarve"],
    ["parchal","Algarve"],
    ["ferragudo","Algarve"],
    ["porches","Algarve"],
    ["tavira (santa maria e santiago)","Algarve"],
    ["tavira (santa maria","Algarve"],
    ["santiago)","Algarve"],
    ["conceicao e cabanas de tavira","Algarve"],
    ["conceicao","Algarve"],
    ["cabanas de tavira","Algarve"],
    ["luz de tavira e santo estevao","Algarve"],
    ["luz de tavira","Algarve"],
    ["santo estevao","Algarve"],
    ["santa catarina da fonte do bispo","Algarve"],
    ["santa luzia","Algarve"],
    ["cachopo","Algarve"],
    ["alvor","Algarve"],
    ["mexilhoeira grande","Algarve"],
    ["lagos (sao sebastiao e santa maria)","Algarve"],
    ["lagos (sao sebastiao","Algarve"],
    ["santa maria)","Algarve"],
    ["odiaxere","Algarve"],
    ["bensafrim e barao de sao joao","Algarve"],
    ["bensafrim","Algarve"],
    ["barao de sao joao","Algarve"],
    ["monte gordo","Algarve"],
    ["odeleite","Algarve"],
    ["azinhal","Algarve"],
    ["alferce","Algarve"],
    ["marmelete","Algarve"],
    ["bordeira","Algarve"],
    ["odeceixe","Algarve"],
    ["rogil","Algarve"],
    ["vila do bispo e raposeira","Algarve"],
    ["raposeira","Algarve"],
    ["budens","Algarve"],
    ["sagres","Algarve"],
    ["alcoutim e pereiro","Algarve"],
    ["pereiro","Algarve"],
    ["gioes","Algarve"],
    ["martim longo","Algarve"],
    ["vaqueiros","Algarve"],
    ["adaufe","Braga"],
    ["braga (sao vicente)","Braga"],
    ["braga (sao vitor)","Braga"],
    ["esporoes","Braga"],
    ["figueiredo","Braga"],
    ["gualtar","Braga"],
    ["lamas","Braga"],
    ["mire de tibaes","Braga"],
    ["padim da graca","Braga"],
    ["palmeira","Braga"],
    ["pedralva","Braga"],
    ["priscos","Braga"],
    ["ruilhe","Braga"],
    ["sequeira","Braga"],
    ["sobreposta","Braga"],
    ["tadim","Braga"],
    ["tebosa","Braga"],
    ["arentim e cunha","Braga"],
    ["arentim","Braga"],
    ["cunha","Braga"],
    ["braga (maximinos, se e cividade)","Braga"],
    ["braga (maximinos","Braga"],
    ["cividade)","Braga"],
    ["braga (sao jose de sao lazaro e sao joao do souto)","Braga"],
    ["braga (sao jose de sao lazaro","Braga"],
    ["sao joao do souto)","Braga"],
    ["cabreiros e passos (sao juliao)","Braga"],
    ["cabreiros","Braga"],
    ["passos (sao juliao)","Braga"],
    ["celeiros, aveleda e vimieiro","Braga"],
    ["celeiros","Braga"],
    ["aveleda","Braga"],
    ["vimieiro","Braga"],
    ["crespos e pousada","Braga"],
    ["crespos","Braga"],
    ["pousada","Braga"],
    ["escudeiros e penso (santo estevao e sao vicente)","Braga"],
    ["escudeiros","Braga"],
    ["penso (santo estevao","Braga"],
    ["sao vicente)","Braga"],
    ["este (sao pedro e sao mamede)","Braga"],
    ["este (sao pedro","Braga"],
    ["sao mamede)","Braga"],
    ["ferreiros e gondizalves","Braga"],
    ["ferreiros","Braga"],
    ["gondizalves","Braga"],
    ["guisande e oliveira (sao pedro)","Braga"],
    ["guisande","Braga"],
    ["oliveira (sao pedro)","Braga"],
    ["lomar e arcos","Braga"],
    ["lomar","Braga"],
    ["arcos","Braga"],
    ["merelim (sao paio), panoias e parada de tibaes","Braga"],
    ["merelim (sao paio)","Braga"],
    ["panoias","Braga"],
    ["parada de tibaes","Braga"],
    ["merelim (sao pedro) e frossos","Braga"],
    ["merelim (sao pedro)","Braga"],
    ["frossos","Braga"],
    ["morreira e trandeiras","Braga"],
    ["morreira","Braga"],
    ["trandeiras","Braga"],
    ["nogueira, fraiao e lamacaes","Braga"],
    ["fraiao","Braga"],
    ["lamacaes","Braga"],
    ["nogueiro e tenoes","Braga"],
    ["nogueiro","Braga"],
    ["tenoes","Braga"],
    ["real, dume e semelhe","Braga"],
    ["real","Braga"],
    ["dume","Braga"],
    ["semelhe","Braga"],
    ["santa lucrecia de algeriz e navarra","Braga"],
    ["santa lucrecia de algeriz","Braga"],
    ["navarra","Braga"],
    ["vilaca e fradelos","Braga"],
    ["vilaca","Braga"],
    ["fradelos","Braga"],
    ["airao (santa maria)","Braga"],
    ["airao (sao joao)","Braga"],
    ["aldao","Braga"],
    ["azurem","Braga"],
    ["barco","Braga"],
    ["brito","Braga"],
    ["caldelas","Braga"],
    ["calvos","Braga"],
    ["candoso (sao martinho)","Braga"],
    ["conde","Braga"],
    ["corvite","Braga"],
    ["costa","Braga"],
    ["creixomil","Braga"],
    ["fermentoes","Braga"],
    ["gandarela","Braga"],
    ["gondar","Braga"],
    ["gonca","Braga"],
    ["guardizela","Braga"],
    ["infantas","Braga"],
    ["longos","Braga"],
    ["mesao frio","Braga"],
    ["moreira de conegos","Braga"],
    ["pencelo","Braga"],
    ["pinheiro","Braga"],
    ["polvoreira","Braga"],
    ["ponte","Braga"],
    ["prazins (santa eufemia)","Braga"],
    ["prazins (santo tirso)","Braga"],
    ["ronfe","Braga"],
    ["sande (sao clemente)","Braga"],
    ["sande (sao martinho)","Braga"],
    ["sande (vila nova)","Braga"],
    ["selho (sao cristovao)","Braga"],
    ["selho (sao jorge)","Braga"],
    ["serzedelo","Braga"],
    ["sao faustino","Braga"],
    ["sao torcato","Braga"],
    ["tabuadelo","Braga"],
    ["urgezes","Braga"],
    ["vermil","Braga"],
    ["abacao e gemeos","Braga"],
    ["abacao","Braga"],
    ["gemeos","Braga"],
    ["arosa e casteloes","Braga"],
    ["arosa","Braga"],
    ["casteloes","Braga"],
    ["ataes e rendufe","Braga"],
    ["ataes","Braga"],
    ["rendufe","Braga"],
    ["briteiros (santo estevao) e donim","Braga"],
    ["briteiros (santo estevao)","Braga"],
    ["donim","Braga"],
    ["briteiros (sao salvador) e briteiros (santa leocadia)","Braga"],
    ["briteiros (sao salvador)","Braga"],
    ["briteiros (santa leocadia)","Braga"],
    ["candoso santiago e mascotelos","Braga"],
    ["candoso santiago","Braga"],
    ["mascotelos","Braga"],
    ["leitoes, oleiros e figueiredo","Braga"],
    ["leitoes","Braga"],
    ["oleiros","Braga"],
    ["oliveira, sao paio e sao sebastiao","Braga"],
    ["oliveira","Braga"],
    ["sao paio","Braga"],
    ["sande (sao lourenco) e balazar","Braga"],
    ["sande (sao lourenco)","Braga"],
    ["balazar","Braga"],
    ["selho (sao lourenco) e gominhaes","Braga"],
    ["selho (sao lourenco)","Braga"],
    ["gominhaes","Braga"],
    ["souto (santa maria), souto (sao salvador) e gondomar","Braga"],
    ["souto (santa maria)","Braga"],
    ["souto (sao salvador)","Braga"],
    ["antas e abade de vermoim","Braga"],
    ["abade de vermoim","Braga"],
    ["arnoso (santa maria e santa eulalia) e sezures","Braga"],
    ["arnoso (santa maria","Braga"],
    ["santa eulalia)","Braga"],
    ["sezures","Braga"],
    ["avidos","Braga"],
    ["bairro","Braga"],
    ["brufe","Braga"],
    ["cabecudos","Braga"],
    ["carreira e bente","Braga"],
    ["carreira","Braga"],
    ["bente","Braga"],
    ["cavaloes","Braga"],
    ["cruz","Braga"],
    ["delaes","Braga"],
    ["esmeriz","Braga"],
    ["gaviao","Braga"],
    ["gondifelos","Braga"],
    ["joane","Braga"],
    ["landim","Braga"],
    ["lemenhe, mouquim e jesufrei","Braga"],
    ["lemenhe","Braga"],
    ["mouquim","Braga"],
    ["jesufrei","Braga"],
    ["louro","Braga"],
    ["lousado","Braga"],
    ["mogege","Braga"],
    ["nine","Braga"],
    ["novais","Braga"],
    ["oliveira (santa maria)","Braga"],
    ["oliveira (sao mateus)","Braga"],
    ["outiz","Braga"],
    ["pedome","Braga"],
    ["pousada de saramagos","Braga"],
    ["requiao","Braga"],
    ["riba de ave","Braga"],
    ["ribeirao","Braga"],
    ["ruivaes","Braga"],
    ["seide","Braga"],
    ["vale (sao cosme), telhado e portela","Braga"],
    ["vale (sao cosme)","Braga"],
    ["telhado","Braga"],
    ["vale (sao martinho)","Braga"],
    ["vila nova de famalicao e calendario","Braga"],
    ["calendario","Braga"],
    ["vilarinho das cambas","Braga"],
    ["abade de neiva","Braga"],
    ["aborim","Braga"],
    ["adaes","Braga"],
    ["airo","Braga"],
    ["aldreu","Braga"],
    ["alheira e igreja nova","Braga"],
    ["alheira","Braga"],
    ["igreja nova","Braga"],
    ["alvelos","Braga"],
    ["alvito (sao pedro e sao martinho) e couto","Braga"],
    ["alvito (sao pedro","Braga"],
    ["sao martinho)","Braga"],
    ["couto","Braga"],
    ["areias de vilar e encourados","Braga"],
    ["areias de vilar","Braga"],
    ["encourados","Braga"],
    ["balugaes","Braga"],
    ["barcelinhos","Braga"],
    ["barqueiros","Braga"],
    ["cambeses","Braga"],
    ["campo e tamel (sao pedro fins)","Braga"],
    ["tamel (sao pedro fins)","Braga"],
    ["carapecos","Braga"],
    ["carreira e fonte coberta","Braga"],
    ["fonte coberta","Braga"],
    ["carvalhal","Braga"],
    ["carvalhas","Braga"],
    ["chorente, goios, courel, pedra furada e gueral","Braga"],
    ["chorente","Braga"],
    ["goios","Braga"],
    ["courel","Braga"],
    ["pedra furada","Braga"],
    ["gueral","Braga"],
    ["cossourado","Braga"],
    ["creixomil e mariz","Braga"],
    ["mariz","Braga"],
    ["cristelo","Braga"],
    ["durraes e tregosa","Braga"],
    ["durraes","Braga"],
    ["tregosa","Braga"],
    ["fornelos","Braga"],
    ["fragoso","Braga"],
    ["galegos (santa maria)","Braga"],
    ["galegos (sao martinho)","Braga"],
    ["gamil e midoes","Braga"],
    ["gamil","Braga"],
    ["midoes","Braga"],
    ["gilmonde","Braga"],
    ["lama","Braga"],
    ["lijo","Braga"],
    ["macieira de rates","Braga"],
    ["manhente","Braga"],
    ["martim","Braga"],
    ["milhazes, vilar de figos e faria","Braga"],
    ["milhazes","Braga"],
    ["vilar de figos","Braga"],
    ["faria","Braga"],
    ["moure","Braga"],
    ["negreiros e chavao","Braga"],
    ["negreiros","Braga"],
    ["chavao","Braga"],
    ["palme","Braga"],
    ["panque","Braga"],
    ["paradela","Braga"],
    ["pereira","Braga"],
    ["perelhal","Braga"],
    ["pousa","Braga"],
    ["quintiaes e aguiar","Braga"],
    ["quintiaes","Braga"],
    ["aguiar","Braga"],
    ["remelhe","Braga"],
    ["rio covo (santa eugenia)","Braga"],
    ["rio covo (santa eulalia)","Braga"],
    ["roriz","Braga"],
    ["sequeade e bastuco (sao joao e santo estevao)","Braga"],
    ["sequeade","Braga"],
    ["bastuco (sao joao","Braga"],
    ["santo estevao)","Braga"],
    ["silva","Braga"],
    ["silveiros","Braga"],
    ["tamel (santa leocadia) e vilar do monte","Braga"],
    ["tamel (santa leocadia)","Braga"],
    ["vilar do monte","Braga"],
    ["tamel (sao verissimo)","Braga"],
    ["ucha","Braga"],
    ["varzea","Braga"],
    ["viatodos, grimancelos, minhotaes e monte de fralaes","Braga"],
    ["viatodos","Braga"],
    ["grimancelos","Braga"],
    ["minhotaes","Braga"],
    ["monte de fralaes","Braga"],
    ["vila boa","Braga"],
    ["vila cova e feitos","Braga"],
    ["vila cova","Braga"],
    ["feitos","Braga"],
    ["vila frescainha (sao martinho)","Braga"],
    ["vila frescainha (sao pedro)","Braga"],
    ["vila seca","Braga"],
    ["afife","Braga"],
    ["alvaraes","Braga"],
    ["amonde","Braga"],
    ["vila nova de anha","Braga"],
    ["areosa","Braga"],
    ["barroselas","Braga"],
    ["cardielos","Braga"],
    ["carreco","Braga"],
    ["castelo do neiva","Braga"],
    ["chafe","Braga"],
    ["darque","Braga"],
    ["freixieiro de soutelo","Braga"],
    ["lanheses","Braga"],
    ["mazarefes","Braga"],
    ["montaria","Braga"],
    ["mujaes","Braga"],
    ["outeiro","Braga"],
    ["perre","Braga"],
    ["santa marta de portuzelo","Braga"],
    ["serreleis","Braga"],
    ["sao romao de neiva","Braga"],
    ["geraz do lima (santa maria, santa leocadia e moreira) e deao","Braga"],
    ["geraz do lima (santa maria","Braga"],
    ["santa leocadia","Braga"],
    ["moreira)","Braga"],
    ["deao","Braga"],
    ["nogueira, meixedo e vilar de murteda","Braga"],
    ["meixedo","Braga"],
    ["vilar de murteda","Braga"],
    ["subportela, deocriste e portela susa","Braga"],
    ["subportela","Braga"],
    ["deocriste","Braga"],
    ["portela susa","Braga"],
    ["torre e vila mou","Braga"],
    ["torre","Braga"],
    ["vila mou","Braga"],
    ["viana do castelo (santa maria maior e monserrate) e meadela","Braga"],
    ["viana do castelo (santa maria maior","Braga"],
    ["monserrate)","Braga"],
    ["meadela","Braga"],
    ["vila franca","Braga"],
    ["vila fria","Braga"],
    ["vila de punhe","Braga"],
    ["aguas santas e moure","Braga"],
    ["calvos e frades","Braga"],
    ["frades","Braga"],
    ["campos e louredo","Braga"],
    ["campos","Braga"],
    ["louredo","Braga"],
    ["covelas","Braga"],
    ["esperanca e brunhais","Braga"],
    ["esperanca","Braga"],
    ["brunhais","Braga"],
    ["fontarcada e oliveira","Braga"],
    ["fontarcada","Braga"],
    ["galegos","Braga"],
    ["garfe","Braga"],
    ["geraz do minho","Braga"],
    ["lanhoso","Braga"],
    ["monsul","Braga"],
    ["rendufinho","Braga"],
    ["santo emiliao","Braga"],
    ["sao joao de rei","Braga"],
    ["sobradelo da goma","Braga"],
    ["taide","Braga"],
    ["travassos","Braga"],
    ["verim, friande e ajude","Braga"],
    ["verim","Braga"],
    ["friande","Braga"],
    ["ajude","Braga"],
    ["vilela","Braga"],
    ["aboim, felgueiras, gontim e pedraido","Braga"],
    ["aboim","Braga"],
    ["gontim","Braga"],
    ["pedraido","Braga"],
    ["agrela e serafao","Braga"],
    ["agrela","Braga"],
    ["serafao","Braga"],
    ["antime e silvares (sao clemente)","Braga"],
    ["antime","Braga"],
    ["silvares (sao clemente)","Braga"],
    ["ardegao, arnozela e seidoes","Braga"],
    ["ardegao","Braga"],
    ["arnozela","Braga"],
    ["seidoes","Braga"],
    ["armil","Braga"],
    ["aroes (santa cristina)","Braga"],
    ["aroes (sao romao)","Braga"],
    ["cepaes e fareja","Braga"],
    ["cepaes","Braga"],
    ["fareja","Braga"],
    ["estoraos","Braga"],
    ["freitas e vila cova","Braga"],
    ["freitas","Braga"],
    ["golaes","Braga"],
    ["medelo","Braga"],
    ["monte e queimadela","Braga"],
    ["monte","Braga"],
    ["queimadela","Braga"],
    ["moreira do rei e varzea cova","Braga"],
    ["moreira do rei","Braga"],
    ["varzea cova","Braga"],
    ["pacos","Braga"],
    ["quinchaes","Braga"],
    ["regadas","Braga"],
    ["revelhe","Braga"],
    ["ribeiros","Braga"],
    ["silvares (sao martinho)","Braga"],
    ["sao gens","Braga"],
    ["vinhos","Braga"],
    ["apulia","Braga"],
    ["belinho","Braga"],
    ["curvos","Braga"],
    ["forjaes","Braga"],
    ["gemeses","Braga"],
    ["marinhas","Braga"],
    ["palmeira de faro","Braga"],
    ["fonte boa e rio tinto","Braga"],
    ["fonte boa","Braga"],
  ],
};
